version: "3"
services:
  info_tlgrm:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    image: info_tlgrm
    volumes:
      - vol_telegram:/var/vol_telegram
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  vol_telegram:
    external: true